[httpClient]
# Specifies a time limit for requests made by the http client
timeout = "60s"
keepAlive = true

[bsc]
baseUri = "https://api.bscscan.com/api"
module = "account"
action = "txlist"
apiKey = "BZEXHK2GFWU5PPAFZJ8MWQ1H4UFMPNYB8Y"
# if rate limit is set to 5 and rateLimitDuration is set to 1s this mean 5reqs/sec
rateLimit = 5
rateLimitPeriod = "1s"

[eth]
baseUri = "https://api.etherscan.io/api"
module = "account"
action = "txlist"
apiKey = "SP2WTJK2N15RQRR2AJC58SGGT58FDDZBUD"
# if rate limit is set to 5 and rateLimitDuration is set to 1s this mean 5reqs/sec
rateLimit = 5
rateLimitPeriod = "1s"

[binance]
baseUri = "https://api.binance.us"
candlesEndpoint = "/api/v3/klines"
currentPriceEndpoint = "/api/v3/avgPrice"
apiKey = "RX3KCdKk4gn095ljB1UJoezVL7OdUo9LeqEdeX7JySk7MKLkQHNN5VWMOC4Or8ek"
bnbusdCurrencySymbol = "BNBBUSD"
ethusdCurrencySymbol = "ETHBUSD"
# if rate limit is set to 1200 and rateLimitDuration is set to 1m this mean 1200reqs/min
rateLimit = 1200
rateLimitDuration = "1m"

[options]
currency = "EUR"

[general]
env = "dev"
